---
- name: Read secrets from HashiCorp Vault using AppRole
  hosts: localhost
  gather_facts: false

  vars:
    vault_addr: "https://vault.example.com"
    role_id: "{{ lookup('env', 'VAULT_AIT_ROLE_ID') }}"
    secret_id: "{{ lookup('env', 'VAULT_AIT_SECRET_ID') }}"
    secret_path: "secret/data/ait123/secret"  
    vault_namespace: "root" 

  tasks:

    - name: Authenticate with Vault using AppRole
      uri:
        url: "{{ vault_addr }}/v1/auth/approle/login"
        method: POST
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Vault-Namespace: "{{ vault_namespace }}"
        body:
          role_id: "{{ role_id }}"
          secret_id: "{{ secret_id }}"
        return_content: yes
        status_code: 200
      register: vault_auth

    - name: Extract Vault token
      set_fact:
        vault_token: "{{ vault_auth.json.auth.client_token }}"

    - name: Read secret from Vault
      uri:
        url: "{{ vault_addr }}/v1/{{ secret_path }}"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Namespace: "{{ vault_namespace }}"
        return_content: yes
        status_code: 200
      register: vault_secret

    - name: Show the retrieved secret
      debug:
        msg: "{{ vault_secret.json.data.data }}" 
